// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import path from "path";
import { defineConfig } from "prisma/config";

// Load .env.local explicitly
dotenv.config({ path: path.resolve(__dirname, ".env.local") });

const databaseUrl = process.env.DATABASE_URL;

// Use a placeholder URL during build if DATABASE_URL is not available
const url = databaseUrl || 'postgresql://localhost:5432/temp';

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: url,
  },
});

