import type { Task, UserStats, LeaderboardEntry } from './types';

export const mockUserStats: UserStats = {
  dailyEarnings: 12.5,
  weeklyEarnings: 67.8,
  totalEarnings: 342.6,
  tasksCompleted: 156,
  currentStreak: 7,
  level: 'Advanced Pioneer',
  availableTasksCount: 24,
};

export const mockTasks: Task[] = [
  {
    id: '1',
    title: 'Test Mobile App Navigation',
    description: 'Test a new mobile app and report any navigation issues',
    category: 'app-testing',
    piReward: 3.5,
    timeEstimate: 15,
    requirements: ['Android or iOS device', 'Stable internet connection'],
    slots: 50,
    slotsRemaining: 23,
    deadline: '2026-02-25',
    employerId: 'emp1',
    employerName: 'TechCorp',
    status: 'available',
    instructions: 'Download the app, test all navigation flows, and submit screenshots of any bugs.',
  },
  {
    id: '2',
    title: 'Complete Consumer Survey',
    description: 'Answer questions about your shopping habits',
    category: 'survey',
    piReward: 2.0,
    timeEstimate: 10,
    requirements: ['Age 18+', 'Regular online shopper'],
    slots: 100,
    slotsRemaining: 67,
    deadline: '2026-02-24',
    employerId: 'emp2',
    employerName: 'MarketResearch Inc',
    status: 'available',
    instructions: 'Complete the survey honestly. All answers are anonymous.',
  },
  {
    id: '3',
    title: 'Translate Product Descriptions',
    description: 'Translate 20 product descriptions from English to Spanish',
    category: 'translation',
    piReward: 8.0,
    timeEstimate: 45,
    requirements: ['Fluent in English and Spanish', 'Translation experience'],
    slots: 10,
    slotsRemaining: 3,
    deadline: '2026-02-26',
    employerId: 'emp3',
    employerName: 'GlobalShop',
    status: 'available',
    instructions: 'Translate accurately maintaining the marketing tone. Submit in provided format.',
  },
  {
    id: '4',
    title: 'Record Voice Samples',
    description: 'Record 50 sentences in your native language',
    category: 'audio-recording',
    piReward: 5.5,
    timeEstimate: 30,
    requirements: ['Quiet environment', 'Clear microphone'],
    slots: 200,
    slotsRemaining: 145,
    deadline: '2026-02-28',
    employerId: 'emp4',
    employerName: 'AI Voice Labs',
    status: 'available',
    instructions: 'Read each sentence clearly in a quiet room. Follow the pronunciation guide.',
  },
  {
    id: '5',
    title: 'Capture Store Photos',
    description: 'Take photos of product displays at your local supermarket',
    category: 'photo-capture',
    piReward: 4.0,
    timeEstimate: 20,
    requirements: ['Smartphone with camera', 'Access to supermarket'],
    slots: 30,
    slotsRemaining: 12,
    deadline: '2026-02-23',
    employerId: 'emp5',
    employerName: 'RetailAnalytics',
    status: 'available',
    instructions: 'Take clear photos of specified product categories. Ensure good lighting.',
  },
  {
    id: '6',
    title: 'Review Content for Accuracy',
    description: 'Review and flag inappropriate or inaccurate content',
    category: 'content-review',
    piReward: 3.0,
    timeEstimate: 25,
    requirements: ['Good attention to detail', 'Age 21+'],
    slots: 75,
    slotsRemaining: 41,
    deadline: '2026-02-27',
    employerId: 'emp6',
    employerName: 'ContentGuard',
    status: 'available',
    instructions: 'Review each item carefully and categorize according to guidelines.',
  },
];

export const mockLeaderboard: LeaderboardEntry[] = [
  { rank: 1, username: 'PiMaster2024', earnings: 1245.8, tasksCompleted: 567 },
  { rank: 2, username: 'TaskHunter', earnings: 1138.2, tasksCompleted: 523 },
  { rank: 3, username: 'PioneerPro', earnings: 1056.5, tasksCompleted: 489 },
  { rank: 4, username: 'EarnDaily', earnings: 987.3, tasksCompleted: 445 },
  { rank: 5, username: 'QuickWorker', earnings: 876.9, tasksCompleted: 412 },
];
